In [1]:
import pickle
import numpy as np

In [2]:
with open('data/drone_dataset.pkl', 'rb') as f:
#with open('data/drone_dataset.pkl', 'rb') as f:
    my_dataset = pickle.load(f)

In [3]:
len(my_dataset)

1254

In [4]:
with open('data/antmaze-large-diverse-v2.pkl', 'rb') as f:
    their_dataset = pickle.load(f)

In [5]:
len(their_dataset)

7182

In [10]:
def dataset_printer(dataset):
    obs, actions, rewards, next_observations, terminals = [], [], [], [], []

    for i in range(len(dataset)):
        obs.extend(dataset[i]['observations'])
        actions.extend(dataset[i]['actions'])
        rewards.extend(dataset[i]['rewards'])
        next_observations.extend(dataset[i]['next_observations'])
        terminals.extend(dataset[i]['terminals'])

    print("observations: \n max: {} min: {}".format(np.max(obs), np.min(obs)))
    print("actions: \n max: {} min: {}".format(np.max(actions), np.min(actions)))
    print("rewards: \n max: {} min: {}".format(np.max(rewards), np.min(rewards)))
    print("next_observations: \n max: {} min: {}".format(np.max(next_observations), np.min(next_observations)))
    print("terminals: \n max: {} min: {}".format(np.max(terminals), np.min(terminals)))

# Example usage:
# dataset = ...
# dataset_printer(dataset)


In [14]:
my_dataset[0]['observations']

array([[ 0.       ,  0.       ,  6.       ,  0.       ],
       [ 0.       ,  0.       ,  7.       , 13.       ],
       [ 0.       ,  0.       ,  8.       ,  7.       ],
       ...,
       [27.       , 26.411076 ,  6.0617423, -2.       ],
       [27.       , 26.12886  ,  6.0617423, -2.       ],
       [27.       , 25.90309  ,  6.0617423, -1.0091665]], dtype=float32)

In [15]:
their_dataset[0]['observations']

array([[ 2.0681225e+01,  2.0770479e+01,  8.0227864e-01, ...,
         4.1167565e-02, -1.6020966e-01, -1.3388745e-01],
       [ 2.0707129e+01,  2.0754622e+01,  8.0514413e-01, ...,
        -5.2111626e+00,  2.6592848e+00,  4.1061316e+00],
       [ 2.0734274e+01,  2.0720472e+01,  6.9769353e-01, ...,
        -2.0019867e+00,  4.2585073e+00,  8.7249488e-01],
       ...,
       [ 2.0908958e+01,  2.4889004e+01,  3.9406788e-01, ...,
         4.3516699e-03, -4.9802189e+00, -1.0022789e+00],
       [ 2.1093866e+01,  2.5025240e+01,  5.4197240e-01, ...,
        -1.5166535e+00,  5.2549690e-01,  9.4781256e-01],
       [ 2.1194805e+01,  2.5031519e+01,  6.4816421e-01, ...,
        -4.0214901e+00,  3.2407510e+00, -1.9735767e+00]], dtype=float32)

In [11]:
dataset_printer(my_dataset)

observations: 
 max: 83.0 min: -2.0
actions: 
 max: 1.0 min: -1.0
rewards: 
 max: 42.0 min: -2.0
next_observations: 
 max: 83.0 min: -2.0
terminals: 
 max: 1.0 min: 0.0


In [12]:
dataset_printer(their_dataset)

observations: 
 max: 37.72719192504883 min: -8.49919319152832
actions: 
 max: 1.0 min: -1.0
rewards: 
 max: 1.0 min: 0.0
next_observations: 
 max: 37.72719192504883 min: -8.49919319152832
terminals: 
 max: 1.0 min: 0.0


In [ ]:
def dataset_printer_single_observations(dataset):
    obs, actions, rewards, next_observations, terminals = [], [], [], [], []

    for i in range(len(dataset)):
        obs.extend(dataset[i]['observations'])
        actions.extend(dataset[i]['actions'])
        rewards.extend(dataset[i]['rewards'])
        next_observations.extend(dataset[i]['next_observations'])
        terminals.extend(dataset[i]['terminals'])

    print("observations: \n max: {} min: {}".format(np.max(obs), np.min(obs)))
    print("actions: \n max: {} min: {}".format(np.max(actions), np.min(actions)))
    print("rewards: \n max: {} min: {}".format(np.max(rewards), np.min(rewards)))
    print("next_observations: \n max: {} min: {}".format(np.max(next_observations), np.min(next_observations)))
    print("terminals: \n max: {} min: {}".format(np.max(terminals), np.min(terminals)))

# Example usage:
# dataset = ...
# dataset_printer(dataset)


In [21]:
my_dataset

[defaultdict(list,
             {'observations': array([[ 0.       ,  0.       ,  6.       ,  0.       ],
                     [ 0.       ,  0.       ,  7.       , 13.       ],
                     [ 0.       ,  0.       ,  8.       ,  7.       ],
                     ...,
                     [27.       , 26.411076 ,  6.0617423, -2.       ],
                     [27.       , 26.12886  ,  6.0617423, -2.       ],
                     [27.       , 25.90309  ,  6.0617423, -1.0091665]], dtype=float32),
              'actions': array([[ 0.        ,  0.        ,  0.9       ],
                     [ 0.        ,  0.        ,  0.85      ],
                     [ 0.        ,  0.        ,  0.8       ],
                     ...,
                     [ 0.        , -0.07055381,  0.        ],
                     [ 0.        , -0.05644305,  0.        ],
                     [ 0.        , -0.04515444,  0.        ]], dtype=float32),
              'rewards': array([13.       ,  7.       ,  2.       , ..

In [129]:
import numpy as np

def convert_to_single_representation(dataset):
    
    observations = [obs for d in dataset for obs in d['observations']]
    actions = [act for d in dataset for act in d['actions']]
    rewards = [rew for d in dataset for rew in d['rewards']]
    next_observations = [next_obs for d in dataset for next_obs in d['next_observations']]
    terminals = [ter for d in dataset for ter in d['terminals']]
    
    obs_min = np.min(observations, axis=0)
    obs_max = np.max(observations, axis=0)
    act_min = np.min(actions)
    act_max = np.max(actions)
    rew_min = np.min(rewards)
    rew_max = np.max(rewards)
    next_obs_min = np.min(next_observations, axis=0)
    next_obs_max = np.max(next_observations, axis=0)
    term_min = np.min(terminals)
    term_max = np.max(terminals)

    print("Observations:")
    print(f"Min: {np.array2string(obs_min, formatter={'float_kind':lambda x: f'{x:.2f}'})}")
    print(f"Max: {np.array2string(obs_max, formatter={'float_kind':lambda x: f'{x:.2f}'})}")
    print("-" * 50)
    print("Actions:")
    print(f"Min: {act_min:.2f}")
    print(f"Max: {act_max:.2f}")
    print("-" * 50)
    print("Rewards:")
    print(f"Min: {rew_min:.2f}")
    print(f"Max: {rew_max:.2f}")
    print("-" * 50)
    print("Next Observations:")
    print(f"Min: {np.array2string(next_obs_min, formatter={'float_kind':lambda x: f'{x:.2f}'})}")
    print(f"Max: {np.array2string(next_obs_max, formatter={'float_kind':lambda x: f'{x:.2f}'})}")
    print("-" * 50)
    print("Terminals:")
    print(f"Min: {term_min}")
    print(f"Max: {term_max}")

In [130]:
convert_to_single_representation(my_dataset)

Observations:
Min: [0.00 0.00 6.00 -2.00]
Max: [83.00 83.00 23.68 42.00]
--------------------------------------------------
Actions:
Min: -1.00
Max: 1.00
--------------------------------------------------
Rewards:
Min: -2.00
Max: 42.00
--------------------------------------------------
Next Observations:
Min: [0.00 0.00 6.02 -2.00]
Max: [83.00 83.00 23.68 42.00]
--------------------------------------------------
Terminals:
Min: 0.0
Max: 1.0


In [131]:
convert_to_single_representation(their_dataset)

Observations:
Min: [-1.15 -1.32 0.20 -1.00 -1.00 -1.00 -1.00 -0.67 -0.10 -0.67 -1.34 -0.67
 -1.34 -0.67 -0.10 -4.00 -4.33 -4.24 -6.66 -6.94 -6.61 -7.54 -6.48 -7.48
 -8.50 -7.55 -7.05 -7.51 -6.38]
Max: [37.73 25.74 1.36 1.00 1.00 1.00 1.00 0.67 1.36 0.67 0.10 0.67 0.10 0.66
 1.36 3.98 3.83 3.25 7.77 6.98 6.99 7.56 8.84 7.53 6.36 7.49 6.34 7.54
 8.74]
--------------------------------------------------
Actions:
Min: -1.00
Max: 1.00
--------------------------------------------------
Rewards:
Min: 0.00
Max: 1.00
--------------------------------------------------
Next Observations:
Min: [-1.15 -1.32 0.20 -1.00 -1.00 -1.00 -1.00 -0.67 0.36 -0.67 -1.34 -0.67
 -1.34 -0.67 0.36 -4.00 -4.33 -4.24 -6.66 -6.94 -6.61 -7.54 -6.48 -7.48
 -8.50 -7.55 -7.05 -7.51 -6.38]
Max: [37.73 25.74 1.36 1.00 1.00 1.00 1.00 0.67 1.36 0.67 -0.36 0.67 -0.35 0.66
 1.36 3.98 3.83 3.25 7.77 6.98 6.99 7.56 8.84 7.53 6.36 7.49 6.34 7.54
 8.74]
--------------------------------------------------
Terminals:
Min: 0.0
Max: 1.0

In [117]:
my_dataset[0]['observations'][0]

array([0., 0., 6., 0.], dtype=float32)

In [116]:
their_dataset[0]['observations'][0]

array([ 2.0681225e+01,  2.0770479e+01,  8.0227864e-01,  9.9558324e-01,
        2.1267341e-02,  9.0396419e-02,  1.3789442e-02, -8.8363305e-02,
        6.9015302e-02,  4.4576764e-02, -1.1765059e-02, -9.6303649e-02,
       -9.0416195e-03,  1.6346876e-02, -7.3636629e-02,  2.1268435e-01,
        3.7563514e-02,  1.9094627e-01,  8.0811821e-02,  6.8205409e-02,
       -1.3908644e-01, -8.0094270e-02, -1.6661269e-03,  1.6283600e-01,
       -6.2213372e-03,  3.6787719e-03,  4.1167565e-02, -1.6020966e-01,
       -1.3388745e-01], dtype=float32)